[package]
name = "decider"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
uefi = { version = "0.36.1", default-features = false, features = ["alloc", "global_allocator", "logger", "panic_handler"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
